/*
DaVinci Copy

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone-davinci

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)


// RolesApiService RolesApi service
type RolesApiService service

type ApiV1CompanySkCompanyIdRolesGetRequest struct {
	ctx context.Context
	ApiService *RolesApiService
	skCompanyId string
}

func (r ApiV1CompanySkCompanyIdRolesGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1CompanySkCompanyIdRolesGetExecute(r)
}

/*
V1CompanySkCompanyIdRolesGet READ Roles

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param skCompanyId
 @return ApiV1CompanySkCompanyIdRolesGetRequest
*/
func (a *RolesApiService) V1CompanySkCompanyIdRolesGet(ctx context.Context, skCompanyId string) ApiV1CompanySkCompanyIdRolesGetRequest {
	return ApiV1CompanySkCompanyIdRolesGetRequest{
		ApiService: a,
		ctx: ctx,
		skCompanyId: skCompanyId,
	}
}

// Execute executes the request
func (a *RolesApiService) V1CompanySkCompanyIdRolesGetExecute(r ApiV1CompanySkCompanyIdRolesGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RolesApiService.V1CompanySkCompanyIdRolesGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/company/{skCompanyId}/roles"
	localVarPath = strings.Replace(localVarPath, "{"+"skCompanyId"+"}", url.PathEscape(parameterToString(r.skCompanyId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1CompanySkCompanyIdRolesPostRequest struct {
	ctx context.Context
	ApiService *RolesApiService
	skCompanyId string
	body *map[string]interface{}
}

func (r ApiV1CompanySkCompanyIdRolesPostRequest) Body(body map[string]interface{}) ApiV1CompanySkCompanyIdRolesPostRequest {
	r.body = &body
	return r
}

func (r ApiV1CompanySkCompanyIdRolesPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1CompanySkCompanyIdRolesPostExecute(r)
}

/*
V1CompanySkCompanyIdRolesPost CREATE Role

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param skCompanyId
 @return ApiV1CompanySkCompanyIdRolesPostRequest
*/
func (a *RolesApiService) V1CompanySkCompanyIdRolesPost(ctx context.Context, skCompanyId string) ApiV1CompanySkCompanyIdRolesPostRequest {
	return ApiV1CompanySkCompanyIdRolesPostRequest{
		ApiService: a,
		ctx: ctx,
		skCompanyId: skCompanyId,
	}
}

// Execute executes the request
func (a *RolesApiService) V1CompanySkCompanyIdRolesPostExecute(r ApiV1CompanySkCompanyIdRolesPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RolesApiService.V1CompanySkCompanyIdRolesPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/company/{skCompanyId}/roles"
	localVarPath = strings.Replace(localVarPath, "{"+"skCompanyId"+"}", url.PathEscape(parameterToString(r.skCompanyId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1CompanySkCompanyIdRolesSkRoleNameDeleteRequest struct {
	ctx context.Context
	ApiService *RolesApiService
	skCompanyId string
	skRoleName string
}

func (r ApiV1CompanySkCompanyIdRolesSkRoleNameDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1CompanySkCompanyIdRolesSkRoleNameDeleteExecute(r)
}

/*
V1CompanySkCompanyIdRolesSkRoleNameDelete DELETE Role

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param skCompanyId
 @param skRoleName
 @return ApiV1CompanySkCompanyIdRolesSkRoleNameDeleteRequest
*/
func (a *RolesApiService) V1CompanySkCompanyIdRolesSkRoleNameDelete(ctx context.Context, skCompanyId string, skRoleName string) ApiV1CompanySkCompanyIdRolesSkRoleNameDeleteRequest {
	return ApiV1CompanySkCompanyIdRolesSkRoleNameDeleteRequest{
		ApiService: a,
		ctx: ctx,
		skCompanyId: skCompanyId,
		skRoleName: skRoleName,
	}
}

// Execute executes the request
func (a *RolesApiService) V1CompanySkCompanyIdRolesSkRoleNameDeleteExecute(r ApiV1CompanySkCompanyIdRolesSkRoleNameDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RolesApiService.V1CompanySkCompanyIdRolesSkRoleNameDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/company/{skCompanyId}/roles/{skRoleName}"
	localVarPath = strings.Replace(localVarPath, "{"+"skCompanyId"+"}", url.PathEscape(parameterToString(r.skCompanyId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"skRoleName"+"}", url.PathEscape(parameterToString(r.skRoleName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest struct {
	ctx context.Context
	ApiService *RolesApiService
	skCompanyId string
	skRoleName string
	body *map[string]interface{}
}

func (r ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest) Body(body map[string]interface{}) ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest {
	r.body = &body
	return r
}

func (r ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest) Execute() (*http.Response, error) {
	return r.ApiService.V1CompanySkCompanyIdRolesSkRoleNamePutExecute(r)
}

/*
V1CompanySkCompanyIdRolesSkRoleNamePut UPDATE Role

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param skCompanyId
 @param skRoleName
 @return ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest
*/
func (a *RolesApiService) V1CompanySkCompanyIdRolesSkRoleNamePut(ctx context.Context, skCompanyId string, skRoleName string) ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest {
	return ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest{
		ApiService: a,
		ctx: ctx,
		skCompanyId: skCompanyId,
		skRoleName: skRoleName,
	}
}

// Execute executes the request
func (a *RolesApiService) V1CompanySkCompanyIdRolesSkRoleNamePutExecute(r ApiV1CompanySkCompanyIdRolesSkRoleNamePutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RolesApiService.V1CompanySkCompanyIdRolesSkRoleNamePut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/company/{skCompanyId}/roles/{skRoleName}"
	localVarPath = strings.Replace(localVarPath, "{"+"skCompanyId"+"}", url.PathEscape(parameterToString(r.skCompanyId, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"skRoleName"+"}", url.PathEscape(parameterToString(r.skRoleName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
